### PR TITLE
Upgrade Kafka to 2.8.0 and associated dependencies

### PR DESCRIPTION
**Pull request by Naicisum**
This PR upgrades Kafka to 2.8.0 and associated dependencies.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by Naicisum** [comment]
My Build Log locally (filtered out non sbt messages)
---------------------------------------------------------
[info] welcome to sbt 1.5.1 (Red Hat, Inc. Java 11.0.11)
[info] loading settings for project cmak-build from plugins.sbt ...
[info] loading project definition from /home/sysop/Documents/Repo/cmak/project
[info] loading settings for project root from build.sbt ...
[info] set current project to cmak (in build file:/home/sysop/Documents/Repo/cmak/)
[success] Total time: 1 s, completed May 6, 2021, 1:39:33 AM
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, libraryDependencies
[info] Reapplying settings...
[info] set current project to cmak (in build file:/home/sysop/Documents/Repo/cmak/)
[info] compiling 135 Scala sources and 2 Java sources to /home/sysop/Documents/Repo/cmak/target/scala-2.12/classes ...
[info] LESS compiling on 1 source(s)
[info] Cleaning datadir [/home/sysop/Documents/Repo/cmak/target/scala-2.12/scoverage-data]
[info] Beginning coverage instrumentation
[info] Instrumentation completed [11880 statements]
[info] Wrote instrumentation file [/home/sysop/Documents/Repo/cmak/target/scala-2.12/scoverage-data/scoverage.coverage]
[info] Will write measurement data to [/home/sysop/Documents/Repo/cmak/target/scala-2.12/scoverage-data]
[info] done compiling
[info] compiling 24 Scala sources to /home/sysop/Documents/Repo/cmak/target/scala-2.12/test-classes ...
[info] done compiling
[info] TestKafkaMetrics:
[info] - generate broker metric name correctly for kafka 0.8.1.1
[info] - generate broker metric name correctly for kafka 0.8.2
[info] - generate broker metric name correctly for kafka 0.9.0
[info] - generate broker metric name correctly for kafka 0.10.0
[info] - generate broker metric name correctly for kafka 0.10.1
[info] - generate broker metric name correctly for kafka 0.10.2
[info] - generate broker metric name correctly for kafka 0.11.0
[info] - generate broker metric name correctly for kafka 1.0.0
[info] - generate broker metric name correctly for kafka 1.1.0
[info] - generate broker metric name correctly for kafka 1.1.1
[info] - generate topic metric name correctly for kafka 0.8.1.1
[info] - generate topic metric name correctly for kafka 0.8.2
[info] - generate topic metric name correctly for kafka 0.9.0
[info] - generate topic metric name correctly for kafka 0.10.0
[info] - generate topic metric name correctly for kafka 0.10.1
[info] - generate topic metric name correctly for kafka 0.10.2
[info] - generate topic metric name correctly for kafka 0.11.0
[info] - generate topic metric name correctly for kafka 1.0.0
[info] - generate topic metric name correctly for kafka 1.1.0
[info] - generate topic metric name correctly for kafka 1.1.1
[info] BrokerIdentityTest:
[info] - successfully parse json with endpoints with sasl
[info] - successfully parse json with endpoints with plaintext
[info] - successfully parse json with unparseable endpoints
[info] - successfully parse json with endpoints with plaintext and sasl
[info] - successfully parse json without endpoints
[info] - successfully parse json with listener names
[info] TestClusterConfig:
[info] - invalid name
[info] - invalid kafka version
[info] - serialize and deserialize 0.8.1.1
[info] - serialize and deserialize 0.8.2.0 +jmx credentials
[info] - serialize and deserialize 0.8.2.0
[info] - serialize and deserialize 0.8.2.1
[info] - serialize and deserialize 0.8.2.2
[info] - deserialize without version, jmxEnabled, and security protocol
[info] - deserialize from 0.8.2-beta as 0.8.2.0
[info] - deserialize from 0.9.0.1
[info] - serialize and deserialize 0.10.0.0
[info] - serialize and deserialize 0.10.1.0
[info] - serialize and deserialize 0.10.1.1
[info] - serialize and deserialize 0.10.2.0
[info] - serialize and deserialize 0.10.2.1
[info] - serialize and deserialize 0.11.0.0
[info] - serialize and deserialize 0.11.0.2
[info] - serialize and deserialize 1.0.0
[info] - serialize and deserialize 1.1.0
[info] - serialize and deserialize 1.1.1
[info] - serialize and deserialize 2.0.0
[info] - serialize and deserialize 2.1.0
[info] - serialize and deserialize 2.1.1
[info] - serialize and deserialize 2.2.0
[info] - serialize and deserialize 2.2.1
[info] - serialize and deserialize 2.2.2
[info] - serialize and deserialize 2.3.0
[info] - serialize and deserialize 2.3.1
[info] - serialize and deserialize 2.4.0
[info] - serialize and deserialize 2.4.1
[info] - serialize and deserialize 2.5.0
[info] - serialize and deserialize 2.5.1
[info] - serialize and deserialize 2.6.0
[info] - serialize and deserialize 2.7.0
[info] - serialize and deserialize 2.8.0
[info] TestKafkaManagerActor:
[info] - add cluster
[info] - update cluster zkhost
[info] - disable cluster
[info] - enable cluster
[info] - update cluster version
[info] - delete cluster
[info] - get all broker views
[info] - update cluster logkafka enabled
[info] - update cluster tuning
[info] - update cluster security protocol
[info] TestKafkaStateCheck:
[info] - get brokers
[info] - get available brokers in non-existing cluster
[info] - get topics
[info] - get topics in non-existing cluster
[info] - get under-replicated partitions
[info] - get under-replicated partitions of non-existing topic in non-existing cluster
[info] - get unavailable partitions
[info] - get unavailable partitions of non-existing topic in non-existing cluster
[info] - topic summary
[info] - get unavailable topic summary
[info] - get unavailable group summary
[info] - get clusters
[info] - get topic identities
[info] - consumers summary
[info] TestReassignPartitions:
[info] - reassign partitions with empty set
[info] - reassign partitions with out of sync partition count
[info] - reassign partitions with out of sync replication factor
[info] - reassign partitions
[info] - reassign partitions already running
[info] TestPreferredReplicaLeaderElection:
[info] - preferred replica leader election with empty set
[info] - preferred replica leader election
[info] - preferred replica leader election already running
[info] TestLogkafkaStateActor:
[info] - get logkafka logkafka id list
[info] - get logkafka config
[info] - get logkafka client
[info] - get logkafka configs
[info] - get logkafka clients
[info] TestBrokerViewCacheActor:
[info] - get broker view
[info] TestLogkafkaViewCacheActor:
[info] TestCreateTopic:
[info] - create topic with empty name
[info] - create topic with invalid name
[info] - create topic with name too long
[info] - create topic with bad chars in name
[info] - create topic with invalid partitions
[info] - create topic with invalid replication
[info] - create topic with # of brokers < replication
[info] - create topic
[info] - create topic - topic already exists
[info] - alter topic - cannot add zero partitions
[info] - alter topic - replication factor greater than num brokers
[info] - alter topic - add partitions
[info] - alter topic - update config
[info] KafkaVersionTest:
[info] - apply method: supported version.
[info] - apply method: Not supported version.
[info] - check supportedVersions
[info] - Sort formSelectList
[info] - unapply
[info] TestKafkaManager:
[info] - add cluster
[info] - create topic
[info] - fail to create topic again
[info] - get topic list
[info] - query request for invalid cluster
[info] - get broker list
[info] - get topic identity
[info] - get cluster list
[info] - get cluster view
[info] - get cluster config
[info] - get cluster context
[info] - get consumer list passive mode
[info] - get consumer identity passive mode for new consumer
[info] - run preferred leader election
[info] - get preferred leader election
[info] - schedule preferred leader election
[info] - cancel scheduled preferred leader election
[info] - generate partition assignments
[info] - generate partition assignments with replication factor
[info] - fail to generate partition assignments with replication factor larger than available brokers
[info] - run reassign partitions
[info] - get reassign partitions
[info] - add topic partitions
[info] - add multiple topics partitions
[info] - update topic config
[info] - delete topic
[info] - fail to delete non-existent topic
[info] - update cluster zkhost
[info] - disable cluster
[info] - enable cluster
[info] - update cluster version
[info] - delete topic not supported prior to 2.0.0
[info] - update cluster logkafka enabled and activeOffsetCache enabled
[info] - update cluster security protocol and sasl mechanism
[info] - create logkafka
[info] - get logkafka identity
[info] - update logkafka config
[info] - delete logkafka
[info] - delete cluster
[info] TestKafkaStateActor:
[info] - get topic list
[info] - get consumer list
[info] - get topic config
[info] - get broker list
[info] - get topic description
[info] - get consumer description
[info] - get all topic descriptions
[info] - get all consumer descriptions
[info] TestCreateLogkafka:
[info] - create logkafka with empty logkafka id
[info] - create logkafka with invalid logkafka id
[info] - create logkafka with logkafka id too long
[info] - create logkafka with bad chars in logkafka id
[info] - create logkafka with empty log path
[info] - create logkafka with invalid log path
[info] - create logkafka with log path too long
[info] - create logkafka with bad chars in log path
[info] - create logkafka with invalid regex filter pattern
[info] - create logkafka with regex filter pattern too long
[info] - create logkafka with invalid line delimiter
[info] TestClusterManagerActor:
[info] - create topic
[info] - fail to create topic again
[info] - get topic list
[info] - get topic config
[info] - get broker list
[info] - get topic description
[info] - get topic descriptions
[info] - get broker view
[info] - generate partition assignments for topic
[info] - get partition assignments for topic
[info] - manual partition assignments for topic
[info] - run preferred leader election for topic
[info] - run reassign partition for topic
[info] - delete topic
[info] - create logkafka
[info] - get logkafka logkafka id list
[info] - get logkafka config
[info] - delete logkafka
[info] Run completed in 3 minutes, 47 seconds.
[info] Total number of tests run: 193
[info] Suites: completed 16, aborted 0
[info] Tests: succeeded 193, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Strategy 'concat' was applied to 3 files (Run the task at debug level to see details)
[info] Strategy 'deduplicate' was applied to a file (Run the task at debug level to see details)
[info] Strategy 'discard' was applied to 125 files (Run the task at debug level to see details)
[info] Strategy 'filterDistinctLines' was applied to 4 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 4 files (Run the task at debug level to see details)
[info] Strategy 'rename' was applied to 14 files (Run the task at debug level to see details)
[warn] Ignored unknown package option FixedTimestamp(Some(1262304000000))
[success] Total time: 296 s (04:56), completed May 6, 2021, 1:44:32 AM
****

**Comment by fanruinet** [comment]
Not sure what happened with CI build. I got the success result too. Maybe it's only a transient error. But I don't know what I can do to rerun the CI.

[info] Run completed in 4 minutes, 3 seconds.
[info] Total number of tests run: 193
[info] Suites: completed 16, aborted 0
[info] Tests: succeeded 193, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Strategy 'concat' was applied to 3 files (Run the task at debug level to see details)
[info] Strategy 'deduplicate' was applied to a file (Run the task at debug level to see details)
[info] Strategy 'discard' was applied to 125 files (Run the task at debug level to see details)
[info] Strategy 'filterDistinctLines' was applied to 4 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 4 files (Run the task at debug level to see details)
[info] Strategy 'rename' was applied to 14 files (Run the task at debug level to see details)
[warn] Ignored unknown package option FixedTimestamp(Some(1262304000000))
[success] Total time: 342 s (05:42), completed Jun 1, 2021, 1:17:18 AM

**Comment by skaluva** [comment]
can this be merged to master branch.. im looking for 2.8.0 support..

**Comment by Naicisum** [comment]
Closed in lieu of https://github.com/yahoo/CMAK/pull/871

**Pull request closed without merging**
